## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Milkweed Ministries"
    title = "Milkweed Ministries"
    # description = "Abiding and Transforming Together"
    authorimage = "/img/milkweed-logo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = false
    # highlightjsstyle = "github"

## Social Accounts
[params.social]
    # instagram = "MilkweedMinistries"
    # linkedin = "<username>"
    # twitter = "<username>"
    facebook = "MilkweedMinistries"
    email = "info@milkweedministries.com"

## Main Menu
[[menu.main]]
    name = "Projects"
    weight = 300
    identifier = "projects"
    url = "/projects/"
[[menu.main]]
    name = "Fasting & Prayer"
    weight = 200
    identifier = "fasting"
    url = "/fasting/"
[[menu.main]]
    name = "Wailing Women"
    weight = 250
    identifier = "wailing-women"
    url = "/wailing-women/"
[[menu.main]]
    name = "About Us"
    identifier = "about"
    weight = 400
    url = "/about/"
