[[items]]
title = "CAST"
image = "images/full/cast-logo.png"
thumb = "images/thumbs/cast-logo.png"
alt = "CAST"
description = "A mix of women + TED-style talks + a variety show with a social justice flare movement."
url = "http://www.castogether.com"
[[items]]
title = "Verses 3 to 5"
image = "images/full/verses3to5-logo.png"
thumb = "images/thumbs/verses3to5-logo.png"
alt = "Hugrid Theme"
description = "A simple grid theme for Hugo. A kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on."
url = ""
[[items]]
title = "Hugrid Theme"
thumb = "images/thumbs/3.png"
alt = "Hugrid Theme"